version: '3.8'

services:
  telegram-audio-player:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
    env_file:
      - .env.production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/config"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      # Mount playlists directory for dynamic updates
      - ./public/playlists:/app/public/playlists:ro
      # Mount styles directory for dynamic updates
      - ./public/styles:/app/public/styles:ro
      # Optional: Mount logs directory
      - ./logs:/app/logs
    networks:
      - telegram-audio-player-network

networks:
  telegram-audio-player-network:
    driver: bridge